name: t20
authors:
  - Daniel Hillerström <hillerstrom@google.com>
description: A domain specific language for kernel-to-kernel transformations
version: 0.0.1-alpha.1
environment:
  sdk: '>=2.0.0 <3.0.0'
executables:
  t20:
dependencies:
  args: ^1.5.0
  kernel:
    path: /usr/local/google/home/hillerstrom/projects/dart-sdk/sdk/pkg/kernel

