name: t20
authors:
  - Daniel Hillerström <hillerstrom@google.com>
description: A domain specific language for kernel-to-kernel transformations
version: 0.5.1-alpha.1
environment:
  sdk: '>=2.1.0 <3.0.0'
executables:
  t20:
dependencies:
  ansicolor: ^1.0.2
  args: ^1.5.0
  built_collection: ^4.1.0
  kernel: ^0.3.5
  path: ^1.6.2
dependency_overrides:
  kernel:
    path: ../sdk/pkg/kernel
