#!/usr/bin/env bash
#
# Executable wrapper for the t20 main script.
#
if [[ ! -z $T20_COMPILER_ENABLE_ASSERTS && $T20_COMPILER_ENABLE_ASSERTS -eq 1 ]]; then
    pub run --enable-asserts t20 $@
else
    pub run t20 $@
fi
exit $?
