#!/usr/bin/env bash
#
# Copyright (c) 2018, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.
#
# Executable wrapper for the t20 main script.
#
if [[ ! -z $T20_COMPILER_ENABLE_ASSERTS && $T20_COMPILER_ENABLE_ASSERTS -eq 1 ]]; then
    pub run --enable-asserts t20 $@
else
    pub run t20 $@
fi
exit $?
